### PR TITLE
package version bump for PR #31

### PR DESCRIPTION
**Pull request by NickTulett**

### CODE REVIEW

**Comment by NickTulett** [comment]
Sure, that could workSent from my Huawei Mobile-------- Original Message --------Subject: Re: [spunjs/selenium-binaries] package version bump for PR #31 (#32)From: Joe Spencer To: spunjs/selenium-binaries CC: Nick Tulett ,Mention @NickTulett wanna be a maintainer with publish access?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spunjs/selenium-binaries","title":"spunjs/selenium-binaries","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/spunjs/selenium-binaries"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jsdevel in #32: @NickTulett wanna be a maintainer with publish access?"}],"action":{"name":"View Pull Request","url":"https://github.com/spunjs/selenium-binaries/pull/32#issuecomment-452985210"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/spunjs/selenium-binaries/pull/32#issuecomment-452985210",
"url": "https://github.com/spunjs/selenium-binaries/pull/32#issuecomment-452985210",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jsdevel** [comment]
@NickTulett are you on npm?

**Comment by jsdevel** [comment]
nvm, i added you as a collaborator on webdriver-sync a while back!

**Comment by NickTulett** [comment]
Yup but then I changed jobs and didn't have any time to even look at it for 2 years. Time flies!

**Comment by jsdevel** [comment]
@NickTulett added you as a collaborator/maintainer/publisher on github and npm

**Pull request merged**
