### PR TITLE
update drivers to last versions (3.0.1, 2.25 & 1.11.1)

### PR DESCRIPTION
**Pull request by alex-fournier**

### CODE REVIEW

**Comment by jsdevel** [comment]
Thanks!

**Comment by jsdevel** [comment]
@alex-fournier can I add you as a maintainer?

**Comment by jsdevel** [comment]
Would you be willing/able to publish to npm?

**Comment by alex-fournier** [comment]
sure, you can add me as a maintainer

**Comment by alex-fournier** [comment]
and yes I can publish to npm

**Comment by jsdevel** [comment]
sweet!

I usually do `npm version minor` for updates like this.  `npm version patch` for small fixes.

I've added you as a GH collaborator so you now have push access.  What's your npm handle?

**Comment by alex-fournier** [comment]
OK!
@alex-fournier on npm

**Comment by jsdevel** [comment]
you're all set!

**Comment by alex-fournier** [comment]
thanks!

**Comment by jsdevel** [comment]
thank you!

> Many hands make light work

**Pull request merged**
